# rasax specific settings
rasax:
 # Other 'rasax' configuration
 # initialUser is the user which is created upon the initial start
of Rasa X
 initialUser:
 # username specifies the name of this user
 username: "admin"
 # password for the Rasa X user
 password: "chandank"

